repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.0"
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "2.2.1"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/crate-ci/typos
    rev: "v1.23.6"
    hooks:
      - id: typos
  - repo: https://github.com/econchick/interrogate
    rev: "1.7.0"
    hooks:
      - id: interrogate
        args: [-v, qiskit_aqt_provider, test]
        pass_filenames: false  # needed if excluding files with pyproject.toml or setup.cfg
  - repo: local
    hooks:
      - id: check-api-models
        name: check generated API models
        entry: ./scripts/api_models.py generate
        language: script
        pass_filenames: false
        always_run: true
