exclude = [
    ".*__pycache__",
    "docs",
    ".*test",
]
source_roots = [
    ".",
]
exact = true
forbid_circular_dependencies = true

[[modules]]
path = "examples"
depends_on = [
    { path = "qiskit_aqt_provider" },
]

[[modules]]
path = "qiskit_aqt_provider"
depends_on = [
    { path = "qiskit_aqt_provider.api_client" },
]

[[modules]]
path = "qiskit_aqt_provider.api_client"
depends_on = []

[[interfaces]]
expose = [
    "DEFAULT_PORTAL_URL",
    "PortalClient",
    "Resource",
    "ResourceType",
    "Workspace",
    "Workspaces",
    "__version__",
    # There are some instances of this, although not included in __all__
    "models.*",
]
from = [
    "qiskit_aqt_provider.api_client",
]

[external]
exclude = [
    "python",
    # if dotenv is not installed (like e.g. in the pre-commit hook's environment)
    # tach cannot know that this is the distribution for dotenv
    # https://github.com/gauge-sh/tach/issues/414
    "python_dotenv",
    "dotenv",
    # pydantic-core always comes with pydantic
    "pydantic_core",
    # testing dependencies:
    "pytest",
    "pytest_sugar",
    "pytest_mock",
    # example dependencies:
    "qiskit_algorithms",
    "qiskit_optimization",
]
