name: Release Artifacts
on:
  push:
    tags:
      - '*'
jobs:
  wheel-build:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'
      - uses: abatilo/actions-poetry@v2
        name: Install Poetry
        with:
          poetry-version: '1.3.2'
      - name: Install Deps
        run: pip install -U twine wheel
      - name: Build Artifacts
        run: |
          poetry build
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/qiskit*
      # - name: Publish to PyPi
      #   env:
      #     TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      #     TWINE_USERNAME: qiskit
      #   run: twine upload dist/qiskit*
      - name: Publish to AQT Package registry
        env:
          TWINE_PASSWORD: ${{ secrets.AQT_PACKAGE_REGISTRY_WRITE_TOKEN }}
          TWINE_USERNAME: github-pypi-python-packages-upload
        run: twine upload --repository-url ${{ secrets.AQT_PACKAGE_REGISTRY_URL }} dist/qiskit*
