name: Release Artifacts
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  wheel-build:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'
      - name: Install release dependencies
        run: pip install -U typer mistletoe
      - name: Build packages
        run: |
          poetry build
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/qiskit*
      - name: Extract changelog
        run: |
          python scripts/extract-changelog.py "${{ github.ref_name }}" | tee "${{ github.workspace }}-CHANGELOG.txt"
      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/qiskit*
          body_path: "${{ github.workspace }}-CHANGELOG.txt"
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
