name: Release Artifacts
on:
  push:
    tags:
      - 'v*'
  # Run on manual triggers
  workflow_dispatch:
jobs:
  release:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    # environment: release
    # permissions:
    #   id-token: write
    #   contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        run: |
          # https://github.com/astral-sh/uv/issues/1386#issuecomment-1947801083
          echo "VIRTUAL_ENV=${Python_ROOT_DIR}" >> $GITHUB_ENV
          pip install uv
      - name: Install release dependencies
        run: |
          uv pip install typer mistletoe hatch
      - name: Build packages
        run: |
          hatch build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/qiskit*
      - name: Extract changelog
        run: python scripts/extract-changelog.py ${{ github.ref_name }} | tee ${{ github.workspace }}-CHANGELOG.txt
      # - name: Create Github release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ./dist/qiskit*
      #     body_path: ${{ github.workspace }}-CHANGELOG.txt
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
